/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaConfiguracion;

import iefi.interfazgrafica.ModeloPersonajes.Heroe;
import iefi.interfazgrafica.ModeloPersonajes.Villano;
import iefi.interfazgrafica.controladores.ControladorPersonajes;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import vistaBatalla.frmBatalla;

/**
 *
 * @author Usuario
 */
public class frmVistaConfiguracion extends javax.swing.JFrame {

    private ControladorPersonajes ctrlHeroe;
    private ControladorPersonajes ctrlVillano;

    /**
     * Creates new form frmVistaConfiguracion
     */
    public frmVistaConfiguracion() {
        initComponents();

        numBnedicion.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        numDenfensa.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        numFuerza.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
        numVida.setModel(new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblApodo = new javax.swing.JLabel();
        lblTipoDePersonaje = new javax.swing.JLabel();
        btnAgregarPersonaje = new javax.swing.JButton();
        txtApodo = new javax.swing.JTextField();
        cbTipoDePersonaje = new javax.swing.JComboBox<>();
        lblVida = new javax.swing.JLabel();
        lblFuerza = new javax.swing.JLabel();
        lblDefensa = new javax.swing.JLabel();
        lblBendicion = new javax.swing.JLabel();
        numVida = new javax.swing.JSpinner();
        numFuerza = new javax.swing.JSpinner();
        numDenfensa = new javax.swing.JSpinner();
        numBnedicion = new javax.swing.JSpinner();
        btnEliminarPersonaje = new javax.swing.JButton();
        lblCantidadBatallas = new javax.swing.JLabel();
        cbCantidadBatallas = new javax.swing.JComboBox<>();
        chbActivarAtaqueSupremo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsPersonajes = new javax.swing.JList<>();
        lblPersonajes = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Configuracion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblApodo.setText("Apodo");

        lblTipoDePersonaje.setText("Tipo de personaje");

        btnAgregarPersonaje.setText("Agregar Personaje");
        btnAgregarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonajeActionPerformed(evt);
            }
        });

        cbTipoDePersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heroe", "Villano" }));

        lblVida.setText("Vida");

        lblFuerza.setText("Fuerza");

        lblDefensa.setText("Defensa");

        lblBendicion.setText("Bendicion");

        btnEliminarPersonaje.setText("Eliminar Personaje");
        btnEliminarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonajeActionPerformed(evt);
            }
        });

        lblCantidadBatallas.setText("Cantidad de batallas");

        cbCantidadBatallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "5" }));

        chbActivarAtaqueSupremo.setText("Activar ataque supremo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApodo)
                                    .addComponent(lblTipoDePersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApodo)
                                    .addComponent(cbTipoDePersonaje, 0, 130, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbActivarAtaqueSupremo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCantidadBatallas)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbCantidadBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblVida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAgregarPersonaje, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblFuerza)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarPersonaje))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDefensa)
                                    .addComponent(lblBendicion))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numBnedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numDenfensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 133, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApodo)
                    .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDePersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoDePersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVida)
                    .addComponent(numVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadBatallas)
                    .addComponent(cbCantidadBatallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuerza)
                    .addComponent(numFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbActivarAtaqueSupremo))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDefensa)
                    .addComponent(numDenfensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBendicion)
                    .addComponent(numBnedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPersonaje)
                    .addComponent(btnEliminarPersonaje))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 410, 260));

        jScrollPane1.setViewportView(lsPersonajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 130, -1));

        lblPersonajes.setText("Personajes");
        getContentPane().add(lblPersonajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 90, -1));

        btnIniciar.setText("Iniciar Batalla");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 30));

        btnCargar.setText("Cargar Batalla");
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 140, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonajeActionPerformed

        try {
            String apodo = txtApodo.getText();
            int vida = ((Number) numVida.getValue()).intValue();
            int defensa = ((Number) numDenfensa.getValue()).intValue();
            int fuerza = ((Number) numFuerza.getValue()).intValue();
            int bendicion = ((Number) numBnedicion.getValue()).intValue();
            String tipo = String.valueOf(cbTipoDePersonaje.getSelectedItem());

            if (tipo.equalsIgnoreCase("Heroe") || tipo.equalsIgnoreCase("Héroe")) {
                if (ctrlHeroe == null) {
                    ctrlHeroe = new ControladorPersonajes(new Heroe());
                }
                ctrlHeroe.crearPersonaje(apodo, vida, defensa, fuerza, bendicion);
            } else if (tipo.equalsIgnoreCase("Villano")) {
                if (ctrlVillano == null) {
                    ctrlVillano = new ControladorPersonajes(new Villano());
                }
                ctrlVillano.crearPersonaje(apodo, vida, defensa, fuerza, bendicion);
            } else {
                throw new IllegalArgumentException("Tipo de personaje inválido: " + tipo);
            }

            actualizarLista();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al crear personaje: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarPersonajeActionPerformed

    private void btnEliminarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonajeActionPerformed
        String seleccionado = lsPersonajes.getSelectedValue();

        if (seleccionado == null) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un personaje para eliminar.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Seguro que querés eliminar este personaje?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        // Detectar por texto en vez de índice
        if (seleccionado.contains("Héroe") || seleccionado.contains("Heroe")) {
            ctrlHeroe = null;
        } else if (seleccionado.contains("Villano")) {
            ctrlVillano = null;
        }

        actualizarLista();
    }//GEN-LAST:event_btnEliminarPersonajeActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Seguro que querés salir del programa?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // Verificar que ambos personajes existan
        if (ctrlHeroe == null || ctrlVillano == null) {
            JOptionPane.showMessageDialog(this,
                    "Debés crear un Héroe y un Villano antes de iniciar la batalla.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int cantidadBatallas = Integer.parseInt(cbCantidadBatallas.getSelectedItem().toString());

        javax.swing.SwingUtilities.invokeLater(() -> {
            this.setVisible(false);
            frmBatalla ventana = new frmBatalla(ctrlHeroe, ctrlVillano, cantidadBatallas);
            ventana.setVisible(true);
            ventana.setLocationRelativeTo(null);
        });
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void actualizarLista() {
        DefaultListModel<String> modeloLista = new DefaultListModel<>();

        if (ctrlHeroe != null && ctrlHeroe.personaje != null) {
            modeloLista.addElement("Héroe: " + ctrlHeroe.personaje.GetApodo());
        }
        if (ctrlVillano != null && ctrlVillano.personaje != null) {
            modeloLista.addElement("Villano: " + ctrlVillano.personaje.GetApodo());
        }

        // Log opcional, también seguro
        String h = (ctrlHeroe != null && ctrlHeroe.personaje != null) ? ctrlHeroe.personaje.GetApodo() : "(sin héroe)";
        String v = (ctrlVillano != null && ctrlVillano.personaje != null) ? ctrlVillano.personaje.GetApodo() : "(sin villano)";
        System.out.println("Estado -> Héroe: " + h + " | Villano: " + v);

        lsPersonajes.setModel(modeloLista);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVistaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVistaConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersonaje;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEliminarPersonaje;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCantidadBatallas;
    private javax.swing.JComboBox<String> cbTipoDePersonaje;
    private javax.swing.JCheckBox chbActivarAtaqueSupremo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApodo;
    private javax.swing.JLabel lblBendicion;
    private javax.swing.JLabel lblCantidadBatallas;
    private javax.swing.JLabel lblDefensa;
    private javax.swing.JLabel lblFuerza;
    private javax.swing.JLabel lblPersonajes;
    private javax.swing.JLabel lblTipoDePersonaje;
    private javax.swing.JLabel lblVida;
    private javax.swing.JList<String> lsPersonajes;
    private javax.swing.JSpinner numBnedicion;
    private javax.swing.JSpinner numDenfensa;
    private javax.swing.JSpinner numFuerza;
    private javax.swing.JSpinner numVida;
    private javax.swing.JTextField txtApodo;
    // End of variables declaration//GEN-END:variables
}
